// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: embd-watch

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_HOME_SCREEN
void ui_HOME_SCREEN_screen_init(void);
lv_obj_t *ui_HOME_SCREEN;
lv_obj_t *ui_BACKGROUND;
lv_obj_t *ui_POWER_BAR;
lv_obj_t *ui_POWER_INDICATOR;
lv_obj_t *ui_TIMETXT;
lv_obj_t *ui_DAYTXT;
lv_obj_t *ui_DATETXT;
lv_obj_t *ui_AMPMTXT;
void ui_event_SETTINGS( lv_event_t * e);
lv_obj_t *ui_SETTINGS;
void ui_event_ARROWUP( lv_event_t * e);
lv_obj_t *ui_ARROWUP;


// SCREEN: ui_SLEEP_SCREEN
void ui_SLEEP_SCREEN_screen_init(void);
void ui_event_SLEEP_SCREEN( lv_event_t * e);
lv_obj_t *ui_SLEEP_SCREEN;
lv_obj_t *ui_BACKGROUNDSLP;
lv_obj_t *ui_ARROWUPSLP;
lv_obj_t *ui_TIMESLPTXT;
lv_obj_t *ui_AMPMSLPTXT;


// SCREEN: ui_SETTINGS_SCREEN
void ui_SETTINGS_SCREEN_screen_init(void);
lv_obj_t *ui_SETTINGS_SCREEN;
lv_obj_t *ui_BACKGROUNDSETTING;
void ui_event_ARROWUPSET( lv_event_t * e);
lv_obj_t *ui_ARROWUPSET;
lv_obj_t *ui_BLUTOOTHTXT;
lv_obj_t *ui_BLUTOOTHSW;
lv_obj_t *ui_WIFITXT;
void ui_event_WIFISW( lv_event_t * e);
lv_obj_t *ui_WIFISW;
lv_obj_t *ui_NTPTXT;
lv_obj_t *ui_NTPSW;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_bg[3] = {&ui_img_bg1_png, &ui_img_bg2_png, &ui_img_bg3_png};
const lv_img_dsc_t *ui_imgset_btn_bg_[3] = {&ui_img_btn_bg_1_png, &ui_img_btn_bg_2_png, &ui_img_btn_bg_3_png};
const lv_img_dsc_t *ui_imgset_call[2] = {&ui_img_call1_png, &ui_img_call2_png};
const lv_img_dsc_t *ui_imgset_heart[1] = {&ui_img_heart2_png};
const lv_img_dsc_t *ui_imgset_s[9] = {&ui_img_s1_png, &ui_img_s2_png, &ui_img_s3_png, &ui_img_s4_png, &ui_img_s5_png, &ui_img_s6_png, &ui_img_s7_png, &ui_img_s8_png, &ui_img_s9_png};
const lv_img_dsc_t *ui_imgset_wave[2] = {&ui_img_wave1_png, &ui_img_wave2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SETTINGS( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_SETTINGS_SCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_SETTINGS_SCREEN_screen_init);
}
}
void ui_event_ARROWUP( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_SLEEP_SCREEN, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SLEEP_SCREEN_screen_init);
}
}
void ui_event_SLEEP_SCREEN( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_HOME_SCREEN, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_HOME_SCREEN_screen_init);
}
}
void ui_event_ARROWUPSET( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_HOME_SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_HOME_SCREEN_screen_init);
}
}
void ui_event_WIFISW( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_state_modify( ui_NTPSW, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
}
if ( event_code == LV_EVENT_RELEASED) {
      _ui_state_modify( ui_NTPSW, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_HOME_SCREEN_screen_init();
ui_SLEEP_SCREEN_screen_init();
ui_SETTINGS_SCREEN_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_HOME_SCREEN);
}
