// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: embd-watch

#include "../ui.h"

void ui_SETTINGS_SCREEN_screen_init(void)
{
ui_SETTINGS_SCREEN = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SETTINGS_SCREEN, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BACKGROUNDSETTING = lv_img_create(ui_SETTINGS_SCREEN);
lv_img_set_src(ui_BACKGROUNDSETTING, &ui_img_grid_png);
lv_obj_set_width( ui_BACKGROUNDSETTING, LV_SIZE_CONTENT);  /// 79
lv_obj_set_height( ui_BACKGROUNDSETTING, LV_SIZE_CONTENT);   /// 212
lv_obj_set_x( ui_BACKGROUNDSETTING, -28 );
lv_obj_set_y( ui_BACKGROUNDSETTING, 0 );
lv_obj_set_align( ui_BACKGROUNDSETTING, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BACKGROUNDSETTING, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BACKGROUNDSETTING, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_BACKGROUNDSETTING,512);
lv_obj_set_style_blend_mode(ui_BACKGROUNDSETTING, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_BACKGROUNDSETTING, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ARROWUPSET = lv_img_create(ui_SETTINGS_SCREEN);
lv_img_set_src(ui_ARROWUPSET, &ui_img_arrow_png);
lv_obj_set_width( ui_ARROWUPSET, LV_SIZE_CONTENT);  /// 18
lv_obj_set_height( ui_ARROWUPSET, LV_SIZE_CONTENT);   /// 12
lv_obj_set_x( ui_ARROWUPSET, 0 );
lv_obj_set_y( ui_ARROWUPSET, 110 );
lv_obj_set_align( ui_ARROWUPSET, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ARROWUPSET, LV_STATE_PRESSED );     /// States
lv_obj_add_flag( ui_ARROWUPSET, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ARROWUPSET, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_ARROWUPSET, 245, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BLUTOOTHTXT = lv_label_create(ui_SETTINGS_SCREEN);
lv_obj_set_width( ui_BLUTOOTHTXT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BLUTOOTHTXT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BLUTOOTHTXT, -90 );
lv_obj_set_y( ui_BLUTOOTHTXT, -45 );
lv_obj_set_align( ui_BLUTOOTHTXT, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_BLUTOOTHTXT,"BLUTOOTH");
lv_obj_set_style_text_color(ui_BLUTOOTHTXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BLUTOOTHTXT, 245, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BLUTOOTHTXT, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BLUTOOTHSW = lv_switch_create(ui_SETTINGS_SCREEN);
lv_obj_set_width( ui_BLUTOOTHSW, 40);
lv_obj_set_height( ui_BLUTOOTHSW, 20);
lv_obj_set_x( ui_BLUTOOTHSW, 60 );
lv_obj_set_y( ui_BLUTOOTHSW, -45 );
lv_obj_set_align( ui_BLUTOOTHSW, LV_ALIGN_CENTER );


ui_WIFITXT = lv_label_create(ui_SETTINGS_SCREEN);
lv_obj_set_width( ui_WIFITXT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WIFITXT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WIFITXT, -90 );
lv_obj_set_y( ui_WIFITXT, -10 );
lv_obj_set_align( ui_WIFITXT, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_WIFITXT,"WIFI");
lv_obj_set_style_text_color(ui_WIFITXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WIFITXT, 245, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WIFITXT, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WIFISW = lv_switch_create(ui_SETTINGS_SCREEN);
lv_obj_set_width( ui_WIFISW, 40);
lv_obj_set_height( ui_WIFISW, 20);
lv_obj_set_x( ui_WIFISW, 60 );
lv_obj_set_y( ui_WIFISW, -10 );
lv_obj_set_align( ui_WIFISW, LV_ALIGN_CENTER );


ui_NTPTXT = lv_label_create(ui_SETTINGS_SCREEN);
lv_obj_set_width( ui_NTPTXT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NTPTXT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_NTPTXT, -90 );
lv_obj_set_y( ui_NTPTXT, 25 );
lv_obj_set_align( ui_NTPTXT, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_NTPTXT,"NTP SYNC");
lv_obj_set_style_text_color(ui_NTPTXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NTPTXT, 245, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_NTPTXT, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NTPSW = lv_switch_create(ui_SETTINGS_SCREEN);
lv_obj_set_width( ui_NTPSW, 40);
lv_obj_set_height( ui_NTPSW, 20);
lv_obj_set_x( ui_NTPSW, 60 );
lv_obj_set_y( ui_NTPSW, 25 );
lv_obj_set_align( ui_NTPSW, LV_ALIGN_CENTER );
lv_obj_add_state( ui_NTPSW, LV_STATE_DISABLED );     /// States


lv_obj_add_event_cb(ui_ARROWUPSET, ui_event_ARROWUPSET, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WIFISW, ui_event_WIFISW, LV_EVENT_ALL, NULL);

}
