// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: embd-watch

#include "../ui.h"

void ui_SLEEP_SCREEN_screen_init(void)
{
ui_SLEEP_SCREEN = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SLEEP_SCREEN, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BACKGROUNDSLP = lv_img_create(ui_SLEEP_SCREEN);
lv_img_set_src(ui_BACKGROUNDSLP, &ui_img_grid_png);
lv_obj_set_width( ui_BACKGROUNDSLP, LV_SIZE_CONTENT);  /// 79
lv_obj_set_height( ui_BACKGROUNDSLP, LV_SIZE_CONTENT);   /// 212
lv_obj_set_x( ui_BACKGROUNDSLP, -28 );
lv_obj_set_y( ui_BACKGROUNDSLP, 0 );
lv_obj_set_align( ui_BACKGROUNDSLP, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BACKGROUNDSLP, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BACKGROUNDSLP, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_BACKGROUNDSLP,512);
lv_obj_set_style_blend_mode(ui_BACKGROUNDSLP, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_BACKGROUNDSLP, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ARROWUPSLP = lv_img_create(ui_SLEEP_SCREEN);
lv_img_set_src(ui_ARROWUPSLP, &ui_img_arrow_png);
lv_obj_set_width( ui_ARROWUPSLP, LV_SIZE_CONTENT);  /// 18
lv_obj_set_height( ui_ARROWUPSLP, LV_SIZE_CONTENT);   /// 12
lv_obj_set_x( ui_ARROWUPSLP, 0 );
lv_obj_set_y( ui_ARROWUPSLP, 110 );
lv_obj_set_align( ui_ARROWUPSLP, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ARROWUPSLP, LV_STATE_PRESSED );     /// States
lv_obj_add_flag( ui_ARROWUPSLP, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ARROWUPSLP, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_ARROWUPSLP, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TIMESLPTXT = lv_label_create(ui_SLEEP_SCREEN);
lv_obj_set_width( ui_TIMESLPTXT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TIMESLPTXT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TIMESLPTXT, -38 );
lv_obj_set_y( ui_TIMESLPTXT, -4 );
lv_obj_set_align( ui_TIMESLPTXT, LV_ALIGN_CENTER );
lv_label_set_text(ui_TIMESLPTXT,"10:32");
lv_obj_set_style_text_color(ui_TIMESLPTXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TIMESLPTXT, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TIMESLPTXT, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AMPMSLPTXT = lv_label_create(ui_SLEEP_SCREEN);
lv_obj_set_width( ui_AMPMSLPTXT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AMPMSLPTXT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AMPMSLPTXT, 40 );
lv_obj_set_y( ui_AMPMSLPTXT, -15 );
lv_obj_set_align( ui_AMPMSLPTXT, LV_ALIGN_CENTER );
lv_label_set_text(ui_AMPMSLPTXT,"AM");
lv_obj_set_style_text_color(ui_AMPMSLPTXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AMPMSLPTXT, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AMPMSLPTXT, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_SLEEP_SCREEN, ui_event_SLEEP_SCREEN, LV_EVENT_ALL, NULL);

}
